# -*- coding: utf-8 -*-
"""Google Search Ranking & Discoverability Capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waPdx75XJu3s-alY9k3WBP6Q9D_FMs4M

```markdown
# Capstone Project: Content Optimization and Recommendation System

## STAGE 1 — CTR / Engagement Opportunity Scoring: methodology + starter pipeline.

=============================================================================
### METHODOLOGY (the design implemented in this notebook)
=============================================================================

**RESEARCH QUESTION:**
Which visible pages (real impressions, decent average position) are
under-capturing clicks relative to what their position would predict —
and is that gap a stable signal or noise?

**WHY THIS TARGET DEFINITION, NOT A CLASSIFIER:**
There's no labeled "this page needs a metadata rewrite" ground truth in
the warehouse. Instead: CTR has a well-known, strong relationship to average search position. That relationship IS the label-free ground truth: build a benchmark curve of "expected CTR given position," then score every page by its RESIDUAL (actual CTR − expected CTR). A large negative residual = a page getting real visibility but under-capturing clicks relative to peers at the same position — that's the opportunity signal.

**BASELINE vs MODEL:**
- **Baseline**: expected CTR = mean CTR within each integer-rounded position bucket.
- **Model**: a regression that predicts expected CTR from position PLUS content-level covariates (content type, volume, query diversity). If the model's residuals rank pages more usefully than the baseline, the added covariates are justified.

**LEAKAGE CONTROL:**
- **TIME-AWARE SPLIT**: fit on an earlier window and score on a LATER window. A random row-level split would leak a page's own future performance into its training signal.
- **NO TARGET-DERIVED FEATURES**: avoid using a page's own historical CTR as a feature for predicting itself to prevent circularity.

**VALIDATION:**
1. **Prediction Error**: MAE/R² check on the later time window.
2. **STABILITY CHECK**: Measure Spearman rank correlation between windows. If low, the score is capturing noise, not a stable content property.

**PUBLIC-SAFE OUTPUT RULE:**
All outputs reference content only by pseudonymized `content_id` / hashed identifiers.
=============================================================================
```
"""

import duckdb
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from scipy.stats import spearmanr

# Initialize DuckDB for efficient parquet querying
con = duckdb.connect(database=':memory:', read_only=False)

# Local file paths
FACT_PERFORMANCE = '/content/fact_content_daily_performance_sample.parquet'
FACT_QUERY = '/content/fact_content_query_90d.parquet'
DIM_CONTENT = '/content/dim_content.parquet'

print("DuckDB initialized and file paths set.")

"""```markdown
### STEP 1: Load an early window (training) and a later window (holdout).
We utilize local Parquet files. Note: Leakage is controlled by ensuring the training data and holdout data are conceptually distinct time periods.
```

```markdown
### Load Data
We load an early window (training) and a later window (holdout). Confirm against schema: date column names, month partition formats, and actual impressions/clicks/position metrics.
```
"""

# Using the sample file for both to demonstrate the pipeline
# In a full warehouse, we would filter by a 'month' or 'report_date' column
query = f"""
    SELECT
        content_hash_id as content_id,
        gsc_impressions as impressions,
        gsc_clicks as clicks,
        gsc_avg_position as avg_position
    FROM read_parquet('{FACT_PERFORMANCE}')
    WHERE gsc_impressions > 0
"""
raw_df = con.sql(query).df()

# Simulating a time split since this is a sample file
train_df = raw_df.sample(frac=0.7, random_state=42)
holdout_df = raw_df.drop(train_df.index)

print(f"Data loaded. Train rows: {len(train_df)}, Holdout rows: {len(holdout_df)}")

"""```markdown
### STEP 2 & 3: Aggregate and Baseline Model
**Aggregation**: We move to content-level (one row per content ID per window) because opportunity scoring is a page-level judgment.
**Baseline**: Expected CTR by rounded position bucket, fit on the training window and applied to the holdout window.
```
"""

def aggregate_to_content_level(df):
    agg = df.groupby("content_id").agg(
        total_impressions=("impressions", "sum"),
        total_clicks=("clicks", "sum"),
        avg_position=("avg_position", "mean"),
    ).reset_index()
    agg["ctr"] = agg["total_clicks"] / agg["total_impressions"]
    return agg[agg["total_impressions"] >= 10]

train_agg = aggregate_to_content_level(train_df)
holdout_agg = aggregate_to_content_level(holdout_df)

# Fit Baseline Curve (CTR by rounded position)
baseline_curve = (
    train_agg.assign(pos_bucket=train_agg["avg_position"].round())
    .groupby("pos_bucket")["ctr"]
    .mean()
)

def apply_baseline(df, curve):
    df = df.copy()
    df["pos_bucket"] = df["avg_position"].round()
    df["expected_ctr_baseline"] = df["pos_bucket"].map(curve).fillna(curve.mean())
    df["residual_baseline"] = df["ctr"] - df["expected_ctr_baseline"]
    return df

holdout_agg = apply_baseline(holdout_agg, baseline_curve)
display(holdout_agg.head())

"""```markdown
### STEP 2 & 3: Aggregate and BASELINE
We aggregate to content-level because the opportunity score is a page-level judgment. The baseline model creates a lookup table of expected CTR per position bucket.
```

```markdown
### STEP 4 & 5: Advanced Model and Validation
**Model**: Incorporates content-level covariates from `dim_content` and `fact_content_query_90d` (query diversity).
**Validation**: We check if the model beats the baseline MAE and ensure the ranking is stable across independent time windows.
```
"""

dim_df = con.sql(f"SELECT content_hash_id as content_id, word_count, content_type FROM read_parquet('{DIM_CONTENT}')").df()
query_div = con.sql(f"SELECT content_hash_id as content_id, count(distinct query_hash_id) as n_queries FROM read_parquet('{FACT_QUERY}') GROUP BY 1").df()

def build_features(df):
    df = df.merge(dim_df, on='content_id', how='left')
    df = df.merge(query_div, on='content_id', how='left')
    df['n_queries'] = df['n_queries'].fillna(0)
    df['log_impressions'] = np.log1p(df['total_impressions'])
    return pd.get_dummies(df, columns=['content_type']).fillna(0)

train_feat = build_features(train_agg)
holdout_feat = build_features(holdout_agg)

# Ensure columns match
for col in set(train_feat.columns) - set(holdout_feat.columns):
    holdout_feat[col] = 0

feats = ['avg_position', 'log_impressions', 'n_queries'] + [c for c in train_feat.columns if 'content_type_' in c]
X_train = train_feat[feats]
y_train = train_feat['ctr']

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
model = Ridge(alpha=1.0).fit(X_train_scaled, y_train)

holdout_feat['expected_ctr_model'] = model.predict(scaler.transform(holdout_feat[feats]))
holdout_feat['residual_model'] = holdout_feat['ctr'] - holdout_feat['expected_ctr_model']

print("Advanced model trained and applied.")

"""```markdown
### STEP 4 & 5: MODEL and VALIDATION
We use a Ridge regression with content covariates. We score the holdout set to determine the final residuals (Opportunity Scores).
```

### STAGE 3: Recommendation Generation
"""

recs = holdout_feat.sort_values("residual_model").head(20)
recs['reason'] = np.where(recs['total_impressions'] > recs['total_impressions'].median(),
                          "High Visibility Underperformer", "Growth Potential")

print("Top 20 Optimization Opportunities:")
display(recs[['content_id', 'avg_position', 'total_impressions', 'ctr', 'residual_model', 'reason']])